### ISSUE TITLE
CutAdapt fails w/ reads shorter than 80 nt

### ISSUE THREAD

**Issue by stenglein-lab** [laurenkleine/taxonomy-nf#2]
This is an issue with the pipeline in general and not with Lauren's implementation of nextflow.

The pipeline runs cutadapt with '--minimum-length 80'  to get rid of reads shorter than 80 bp.  This works most of the time because our typical reads are 150 bases long.  But this won't always be true, e.g. for 2x75 runs or for SRA datasets or datasets from others.

This causes cutadapt to fail in a cryptic manner when it's fed reads shorter than 80 bases long.  

I'm not sure what the best work around is.  A few not necessarily mutually exclusive options:

- Check the size of the reads in the file. If shorter than the the --minimum-length parameter, die with a cryptic error.  
- Parameterize this setting in the nextflow.config
- Modify the value of this parameter on the fly, depending on the average read length (e.g. 1/2 of average read length).

**Comment by laurenkleine** [comment]
I added the 'min_len' parameter in nextflow.config, and edited main.nf accordingly. I tested the pipeline to make sure everything still worked as it should, and it does. 

So now we should be able to modify this value on the fly!
