### ISSUE TITLE
Degree of parallelization should be configurable

### ISSUE THREAD

**Issue by stenglein-lab** [laurenkleine/taxonomy-nf#3]
The # of simultaneous datasets that get processed should be configured and limited to 4 or 6 by default.  I think this might be controlled by code like this in nextflow.config:

executor {
    queueSize = 4    // number of datasets that will be processed in parallel 
}

The rationales for not running all available datasets at once in parallel are:

- one of the main resource bottlenecks is hard drive I/O, and if all the datasets are running in parallel they will end up blocking on I/O a lot, which is not efficient
- some of the steps in the pipeline use a lot of RAM and/or CPUs, so we want to limit that too.

**Comment by laurenkleine** [comment]
I made this alteration in nextflow.config. Thank you for catching this and for recommending a solution.
